# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - script: echo Build First Job
      - script: echo $(PipelineLevelVariable)
      - script: echo $(Build.BuildNumber)
      - script: echo $(Build.BuildId)
      - script: echo $(Build.SourceBranchName)
      - script: echo $(Build.SourcesDirectory)
      - script: echo $(System.DefaultWorkingDirectory)
      - script: ls -r  $(System.DefaultWorkingDirectory)
      - script: echo $(Build.ArtifactStagingDirectory)